#!/usr/bin/env bash

# verify arguments
if [ $# -ne 2 ] ; then
  echo "Usage: kattis [problem] [language]"
  exit 1
fi
problem=$1
language=$2

# establish KATTISROOT
if [ -z $KATTISROOT ] ; then
  echo "No default \$KATTISROOT is set on this device."
  echo "Please enter your Kattis home directory: "
  read KATTISROOT
fi
if [ ! -d $KATTISROOT ] ; then
  echo "Invalid Kattis root directory (${KATTISROOT})."
  exit 1
fi
cd $KATTISROOT

# resolve language aliases
if [ ! -d templates/${language} ] ; then
  found=""
  for template in $(ls templates) ; do
    if [ ! -z $(grep "^${language}$" templates/${template}/aliases) ] ; then
      language=$template
      found="y"
      break
    fi
  done
  if [ -z $found ] ; then
    echo "Unknown language '${language}'."
    exit 1
  fi
fi
if [ -d problems/${problem}/${language} ] ; then
  echo "A ${language} solution for ${problem} already exists."
  exit 1
fi

# set up template
mkdir -p problems/${problem}
cp -r templates/${language} problems/${problem}
cd problems/${problem}/${language}
./template ${problem}
rm aliases template
echo "${language} template created at problems/${problem}/${language}"
