#!/usr/bin/env bash
if [ ! -f ../.kattispage ] || [ ! -f .kattisrunner ]; then
    echo "Error: not a Kattis solution directory."
    exit 1
fi
runner=$(cat .kattisrunner)
if [ ! -f ${KATTISROOT}/scripts/run/${runner} ]; then
    echo "Error: no run configuration named '${runner}'."
    exit 1
fi
problem=$(basename $(dirname $(pwd)))
solution=$(basename $(pwd))
testdir=../tests
testcount=$(( $(ls -1 ${testdir} | wc -l) / 2 ))
echo "Checking ${problem}/${solution} against ${testcount} test sample(s)..."
testlimit=$((testcount - 1))
allpassing="y"
for testnum in $(seq 0 ${testlimit}); do
    ${KATTISROOT}/scripts/run/${runner} ${problem} \
        < ${testdir}/${testnum}.tst \
        &> check.out
    if diff check.out ${testdir}/${testnum}.out >/dev/null; then
      :
    else
        echo ""
        echo "Test ${testnum} failed."
        echo "---  Given:   ---"
        cat ${testdir}/${testnum}.tst
        echo "--- Expected: ---"
        cat ${testdir}/${testnum}.out
        echo "---  Actual:  ---"
        cat check.out
        allpassing="n"
    fi
done
if [ -f check.out ]; then
    rm check.out
fi
if [ ${allpassing} == "y" ]; then
    echo "All tests passing."
fi
