#!/usr/bin/env python3
from os import mkdir
from os.path import isfile, isdir
from string import whitespace
from sys import stderr

import requests
from bs4 import BeautifulSoup

TEST_DIR_NAME = "tests"
PAGE_FILE_NAME = ".kattispage"


def process(s: str) -> str:
    if all(map(lambda x: x in whitespace, s)):
        return s
    if s[0] == "\n":
        return s[1:]
    return s


def setup():
    if not isfile(PAGE_FILE_NAME):
        print("Error: not a Kattis problem directory.")
        exit(1)
    if not isdir(TEST_DIR_NAME):
        mkdir(TEST_DIR_NAME)


def get_url() -> str:
    with open(PAGE_FILE_NAME, "rt") as file:
        url = file.readline().strip()
        if not url.startswith("https://"):
            url = "https://" + url
    return url


def get_tests(url: str) -> list[str]:
    req = requests.get(url)
    if not req.ok:
        print(f"Error: unable to reach {url}: "
              f"{req.status_code} {req.reason}",
              file=stderr)
        exit(1)
    soup = BeautifulSoup(req.text, "lxml")
    tests = [
        process(pre.text)
        for t in soup.find_all("table")
        if "sample" in t.get_attribute_list("class")
        for pre in t.find_all("pre")
    ]
    return tests


def write_tests(tests: list[str]):
    for i in range(len(tests) // 2):
        with open(f"{TEST_DIR_NAME}/{i}.in", "wt", encoding="utf-8") as file:
            file.write(tests[i * 2])
        with open(f"{TEST_DIR_NAME}/{i}.out", "wt", encoding="utf-8") as file:
            file.write(tests[i * 2 + 1])


def main():
    setup()
    url = get_url()
    tests = get_tests(url)
    write_tests(tests)


if __name__ == "__main__":
    main()
