#!/usr/bin/env python3
from http.client import HTTPS_PORT, HTTPSConnection
from os import mkdir, sep
from os.path import isfile, isdir
from sys import argv

TEST_DIR_NAME = "tests"
PROBLEM_FILE_NAME = ".kattisproblem"
PAGE_FILE_NAME = ".kattispage"


def main(contest_name):
    if not isfile(PROBLEM_FILE_NAME):
        print("Error: not a Kattis problem directory.")
        exit(1)
    with open(PROBLEM_FILE_NAME, "rt") as file:
        problem_name = file.read().strip()
    if not isdir(TEST_DIR_NAME):
        mkdir(TEST_DIR_NAME)
    domain_name = f"{contest_name or 'open'}.kattis.com"
    path_name = f"/problems/{problem_name}"
    if contest_name:
        path_name = f"/contests/{contest_name}" + path_name
    with open(PAGE_FILE_NAME, "wt") as file:
        file.write(f"https://{domain_name}{path_name}")
    conn = HTTPSConnection(domain_name, HTTPS_PORT)
    conn.request("GET", path_name)
    resp = conn.getresponse()
    content = resp.read()
    fields = [s.split(b"</pre>")[0].strip()
              for s in content.split(b"<pre>")[1:]]
    for i in range(len(fields) // 2):
        with open(TEST_DIR_NAME + sep + f"{i}.tst", "wb") as file:
            file.write(fields[i * 2])
            file.write(b"\n")
        with open(TEST_DIR_NAME + sep + f"{i}.out", "wb") as file:
            file.write(fields[i * 2 + 1])
            file.write(b"\n")


if __name__ == "__main__":
    main(argv[1] if len(argv) >= 2 else None)
