#!/usr/bin/env bash

# verify arguments
if [ $# -ne 2 ]; then
    echo "Usage: kattis [problem] [language]"
    exit 1
fi
problem=$1
language=$2

# establish KATTISROOT
if [ -z ${KATTISROOT} ]; then
    echo "No default \$KATTISROOT is set on this device."
    echo "Please enter your Kattis home directory: "
    read KATTISROOT
fi
if [ ! -d ${KATTISROOT} ]; then
    echo "Error: invalid Kattis root directory (${KATTISROOT})."
    exit 1
fi
cd ${KATTISROOT}

# initialize problem directory
if [ ! -d problems/${problem} ]; then
    mkdir -p problems/${problem}
    cd problems/${problem}
    echo ${problem} > .kattisproblem
    ${KATTISROOT}/scripts/download_tests
    cd ${KATTISROOT}
fi

# resolve language aliases
if [ ! -d templates/${language} ]; then
    found="n"
    for template in $(ls templates); do
        if [ ! -z $(grep "^${language}$" templates/${template}/aliases) ]; then
            language=$template
            found="y"
            break
        fi
    done
    if [ $found = "n" ]; then
        echo "Error: unknown language '${language}'."
        exit 1
    fi
fi
if [ -d problems/${problem}/${language} ]; then
    echo "Error: a ${language} solution for ${problem} already exists."
    exit 1
fi

# copy template and initialize solution directory
cp -r templates/${language} problems/${problem}
cd problems/${problem}/${language}
echo ${language} > .kattislanguage
./template ${problem}
rm aliases template run
ln -s ${KATTISROOT}/scripts/check
echo "${language} template created at problems/${problem}/${language}"
